### ISSUE TITLE
RetriesExhaustedError

### ISSUE THREAD

**Issue by aparnabharathan1995** [HewlettPackard/python-ilorest-library#55] opened 2019-05-08 06:09 UTC
While running the quickstart.py example i am getting the following error. 

Traceback (most recent call last):
  File "quickstart.py", line 16, in <module>
    REDFISH_OBJ = redfish.redfish_client(base_url=login_host, username=login_account,password=login_password, default_prefix='/redfish/v1')
  File "/home/vkchlt0163/.local/lib/python3.5/site-packages/redfish/rest/v1.py", line 1027, in redfish_client
    max_retry=max_retry)
  File "/home/vkchlt0163/.local/lib/python3.5/site-packages/redfish/rest/v1.py", line 952, in __init__
    max_retry=max_retry)
  File "/home/vkchlt0163/.local/lib/python3.5/site-packages/redfish/rest/v1.py", line 422, in __init__
    self.get_root_object()
  File "/home/vkchlt0163/.local/lib/python3.5/site-packages/redfish/rest/v1.py", line 553, in get_root_object
    raise excp
  File "/home/vkchlt0163/.local/lib/python3.5/site-packages/redfish/rest/v1.py", line 551, in get_root_object
    resp = self.get('%s%s' % (self.__url.path, self.default_prefix))
  File "/home/vkchlt0163/.local/lib/python3.5/site-packages/redfish/rest/v1.py", line 585, in get
    headers=headers)
  File "/home/vkchlt0163/.local/lib/python3.5/site-packages/redfish/rest/v1.py", line 979, in _rest_request
    args=args, body=body, headers=headers)
  File "/home/vkchlt0163/.local/lib/python3.5/site-packages/redfish/rest/v1.py", line 844, in _rest_request
    raise RetriesExhaustedError()
redfish.rest.v1.RetriesExhaustedError

Can anyone please help me out.

**Comment by Yergidy** [comment] 2019-05-08 18:56
Hi, what version of urllib3 are you using?

**Comment by aparnabharathan1995** [comment] 2019-05-09 05:06
I am using urllib3-1.25.2

**Comment by aparnabharathan1995** [comment] 2019-05-09 05:17
I am able to do ssh to the host so i believe the login credentials are correct
The following is the script which i ran


import sys
import redfish

# When running remotely connect using the address, account name, 
# and password to send https requests
login_host = "https://***.***.***.***"
login_account = "*********"
login_password = "****"

## Create a REDFISH object
REDFISH_OBJ = redfish.redfish_client(base_url=login_host, username=login_account,password=login_password, default_prefix='/redfish/v1')

# Login into the server and create a session
REDFISH_OBJ.login(auth="session")

# Do a GET on a given path
response = REDFISH_OBJ.get("/redfish/v1/systems/1", None)


# Print out the response
#sys.stdout.write("%s\n" % response)

# Logout of the current session
REDFISH_OBJ.logout()

**Comment by Yergidy** [comment] 2019-05-09 16:48
I am going to close this as it looks like a duplicate of issue #46.

**Closed by Yergidy** 2019-05-09 16:48 UTC
Labels: duplicate
