### ISSUE TITLE
redfish.rest.v1.RetriesExhaustedError

### ISSUE THREAD

**Issue by bonzai1990** [HewlettPackard/python-ilorest-library#26] opened 2018-03-20 09:57 UTC
REST_OBJ = RestObject(iLO_host, iLO_user, iLO_password)
  File "/root/server_restart_ilo/_restobject.py", line 88, in __init__
    default_prefix="/rest/v1")
  File "build/bdist.linux-x86_64/egg/redfish/rest/v1.py", line 1489, in rest_client
  File "build/bdist.linux-x86_64/egg/redfish/rest/v1.py", line 1531, in get_client_instance
  File "build/bdist.linux-x86_64/egg/redfish/rest/v1.py", line 1109, in __init__
  File "build/bdist.linux-x86_64/egg/redfish/rest/v1.py", line 524, in __init__
  File "build/bdist.linux-x86_64/egg/redfish/rest/v1.py", line 652, in get_root_object
redfish.rest.v1.RetriesExhaustedError
Exception AttributeError: "'RestObject' object has no attribute 'rest_client'" in <bound method RestObject.__del__ of <_restobject.RestObject object at 0x1329710>> ignored

What am I missing that it is not working????

**Comment by bonzai1990** [comment] 2018-03-20 09:58
I am trying to connect to ILO 4 - 2.54

**Comment by Yergidy** [comment] 2018-03-26 21:07
I am unable to reproduce this error. It looks like it's unable to connect to the server you are trying to access. Are you sure you can reach the server from the location you are trying to connect from?

**Comment by Yergidy** [comment] 2018-05-10 15:27
If there are no other questions I will be closing this issue.

**Closed** 2018-05-17 21:53 UTC
