### ISSUE TITLE
Lot of Timeout connection error port 443

### ISSUE THREAD

**Issue by shaikk-arch** [HewlettPackard/python-ilorest-library#92] opened 2020-07-30 19:38 UTC
Using "hpilo" library , to upgrade HP BIOS and ILO firmware 
For Model - XL170r i see lot of Timeout connection while connecting to the ilo with Port 443 
Do you know why i am seeing this error ? is there any alternative way to handle this error and upgrade ?

**Comment by KeepSummerSaf3** [comment] 2020-08-12 20:22
Could you verify latency and routing is not an issue with access to the web server?

**Comment by shaikk-arch** [comment] 2020-08-27 06:57
Hi 
There is no issue with the webserver at all "latency and routing " is not an issue 
The issue is still there 
Could you please check and give a fix on this error

**Comment by KeepSummerSaf3** [comment] 2020-08-27 17:21
Suggest to contact HPE support for dedicated troubleshooting on this matter. In the meantime, please provide the iLO version in use. We require some further information.

Can you verify the issue is present if the client and server reside on the same subnet?

Additionally, please list the results for each if NAT or firewalls are in use:
- a ping test from client to server indicating TTL values
- trace route from client to server indicating the full list of nodes. Repeat a few times to verify the routing is the same.

Time connection attempts to /redfish/v1 as well as an authenticated resource such as /redfish/v1/managers/1. If significant variations in time are occurring between responses, to the same resource, please note the type or path for which this is occurring.

**Comment by shaikk-arch** [comment] 2020-08-27 22:17
Hi, 

Ip is reachable , only on few servers i see this "Time out" issue using "HPILO"  
Other wise i can reach ILO

**Comment by KeepSummerSaf3** [comment] 2020-08-27 22:38
Still need the above information. Since this is a probably a specific issue to a subset of systems then HPE support should be able to help isolate the problem for your specific environment.

**Comment by shaikk-arch** [comment] 2020-08-27 22:42
Sure, Let me check with HPE 
Thanks for checking :)

**Comment by rajeevkallur** [comment] 2021-06-07 14:56
Closing this issure. Please retest with latest library version and open a new case if needed

**Closed by rajeevkallur** 2021-06-07 14:56 UTC
